name: create patch

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Checkout oscam-emu-patch
        uses: actions/checkout@v4
        with:
          repository: oscam-mirror/oscam-emu-patch
          token: ${{ github.token }}
          path: emu
          fetch-depth: 0

      - name: Create patch
        run: |
          set -e

          git diff origin/oscam-gitlab -- \
            ':^.github' \
            ':^.gitlab' \
            > emu/oscam-emu.patch

          sed -i "1s/^/patch version: $(./config.sh --oscam-version) ($(./config.sh --oscam-commit))\npatch date: $(date '+%Y-%m-%d %H:%M:%S %Z (%:z)')\n---\n/" emu/oscam-emu.patch

      - name: Commit oscam-emu.patch
        run: |
          set -e

          cd emu

          git config user.name "oscam-emu-bot"
          git config user.email "187860193+oscam-emu-bot@users.noreply.github.com"

          if ! git diff --quiet HEAD; then
            git add oscam-emu.patch
            git commit -m "Sync patch with $(../config.sh --oscam-version)"
            git push origin HEAD:master
          else
            echo "No changes to commit."
          fi
