name: sync gitlab

on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types:
      - invoke-sync-gitlab

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oscam-gitlab
        uses: actions/checkout@v4
        with:
          ref: oscam-gitlab
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Git config
        run: |
          git config user.name "oscam-emu-bot"
          git config user.email "187860193+oscam-emu-bot@users.noreply.github.com"

      - name: Sync oscam-gitlab with upstream
        run: |
          set -e

          git remote add --track master mirror https://github.com/oscam-mirror/oscam.git
          git fetch mirror

          ahead=$(git rev-list mirror/master..HEAD --count)

          if [ "$ahead" -gt 0 ]; then
            force='--force'

            printf '\n%s commit(s) ahead upstream -> reset branch and force push changes\n' "$ahead"

            git reset --hard "HEAD~$ahead"
          fi

          git merge mirror/master

          if [ -n "${force:-}" ]; then
            git push --follow-tags origin --force
          else
            git push --follow-tags origin
          fi

  reuse:
    uses: ./.github/workflows/merge-gitlab.yml
    secrets: inherit
    needs:
      - sync
